version: "3"

services:
  http-log-server:
    build:
      dockerfile: server.dockerfile
      context: ./
    command:
      - "-l"
      - ":8001"
    ports:
      - 8001:8001
    volumes:
      - ./configs:/src/configs
      - ./secrets:/src/secrets
      - ./:/src
    networks:
      - fullstack
  http-log-client:
    build:
      dockerfile: client.dockerfile
      context: ./
    command:
      - "-d"
      - "http-log-server:8001"
    networks:
      - fullstack
    depends_on:
      - http-log-server
    links:
      - http-log-server
    restart: on-failure:5
networks:
  fullstack:
    driver: bridge
