version: "3"

services:
  hermes-leader:
    build:
      dockerfile: debug-hermes.dockerfile
      context: ./
    volumes:
      - ./data/hermes/:/data/hermes/
    environment:
      - NODE_ID=hermes-leader
      - PROTOCOL_IP=localhost
      - PROTOCOL_PORT=10000
    ports:
      - 8000:8000
      - 9000:9000
      - 10000:10000
      - 2345:2345
    command: "--listen=:2345 --headless=true --log=true --log-output=debugger,debuglineerr,gdbwire,lldbout,rpc --accept-multiclient --api-version=2 exec ./hermes"
    network_mode: host
