version: "3"

services:
  http-log-server:
    image: lptonussi/public:http-log-server
    environment:
      - NODE_ID=http-log-server
    command:
      - "--address=localhost"
      - "--port=8001"
    ports:
      - 8001:8001
    network_mode: host
  # http-log-client:
  #   image: lptonussi/public:http-log-server
  #   environment:
  #     - NODE_ID=http-log-client
  #   command:
  #     - "--address=hermes-leader"
  #     - "--port=8000"
  #   network_mode: host
  #   depends_on:
  #     - http-log-server
  #   restart: on-failure:1
  hermes-leader:
    build:
      dockerfile: debug-hermes.dockerfile
      context: ./
    volumes:
      - ./data/hermes/:/data/hermes/
    environment:
      - NODE_ID=hermes-leader
      - PROTOCOL_IP=localhost
      - PROTOCOL_PORT=10000
    ports:
      - 2345:2345
    command: "--listen=:2345 --headless=true --log=true --log-output=debugger,debuglineerr,gdbwire,lldbout,rpc --accept-multiclient --api-version=2 exec ./hermes"
    network_mode: host
    depends_on:
      - http-log-server
