version: "3"

services:
  debug-http-log-server:
    build:
      dockerfile: debug-server.dockerfile
      context: ./
      args:
        - "-l"
        - "localhost:8001"
    ports:
      - 8001:8001
      - 2345:2345
    command: "--listen=:2345 --headless=true --log=true --log-output=debugger,debuglineerr,gdbwire,lldbout,rpc --accept-multiclient --api-version=2 exec ./http-log-server"
