version: "3"

services:
  http-log-server:
    image: lptonussi/public:http-log-server
    environment:
      - NODE_ID=http-log-server
    network_mode: host
  http-log-client:
    image: lptonussi/public:http-log-client
    environment:
      - NODE_ID=http-log-client
  hermes-leader:
    build:
      dockerfile: hermes.dockerfile
      context: ./
    volumes:
      - /tmp/hermesfiles/:/data/
    environment:
      - NODE_ID=localhost
      - PROTOCOL_IP=localhost
      - PROTOCOL_PORT=10000
    depends_on:
      - http-log-server
    ports:
      - 8000:8000
      - 9000:9000
      - 10000:10000
    network_mode: host
