version: "3"

services:
  hermes-followers:
    build:
      dockerfile: hermes.dockerfile
      context: ./
    volumes:
      - /tmp/data/hermes/:/data/hermes/
    environment:
      - NODE_ID=localhost
      - PROTOCOL_IP=localhost
      - PROTOCOL_PORT=10000
    ports:
      - 8000:8000
      - 9000:9000
      - 10000:10000
    network_mode: host
