version: "3"

services:
  hermes-leader:
    build:
      dockerfile: hermes.dockerfile
      context: ./
    environment:
      - NODE_ID=hermes-leader
    command:
      - "-d"
      - ":8001"
  hermes-follower:
    build:
      dockerfile: hermes.dockerfile
      context: ./
    environment:
      - NODE_ID=hermes-follower
    command:
      - "-j"
      - "hermes-leader:9000"
    depends_on:
      - hermes-leader
networks:
  fullstack:
    driver: bridge
