version: "3"

services:
  http-log-server:
    image: lptonussi/public:http-log-server
    environment:
      - NODE_ID=http-log-server
    network_mode: host
  # http-log-client:
  #   build:
  #     dockerfile: client.dockerfile
  #     context: ./
  #   environment:
  #     - NODE_ID=http-log-client
  #   command:
  #     - "-d"
  #     - "hermes-leader:8000"
  #   networks:
  #     - fullstack
  #   depends_on:
  #     - http-log-server
  #   links:
  #     - http-log-server
  #   restart: on-failure:5

  hermes-leader:
    build:
      dockerfile: hermes.dockerfile
      context: ./
    environment:
      - NODE_ID=hermes-leader
    network_mode: host
    depends_on:
      - http-log-server
    # ports:
    #   - 8000:8000
    # depends_on:
    #   - http-log-server
    #   - http-log-client
  # hermes-follower:
  #   build:
  #     dockerfile: hermes.dockerfile
  #     context: ./
  #   environment:
  #     - NODE_ID=hermes-follower
  #   command:
  #     - "-j"
  #     - "hermes-leader:9000"
  #   ports:
  #     - 9000:9000
  #     - 10000:10000
  #   depends_on:
  #     - hermes-leader
  #     - http-log-server
  #     - http-log-client
# networks:
#   fullstack:
#     driver: bridge
