version: "3"

services:
  http-log-server:
    build:
      dockerfile: mock-hashicorp-raft-join-server.dockerfile
      context: ./
    command:
      - "-l"
      - ":9000"
    ports:
      - 9000:9000
    network_mode: "host"
