version: "3"

services:
  http-log-server:
    build:
      dockerfile: server.dockerfile
      context: ./
    command:
      - "-l"
      - ":8001"
    ports:
      - 8001:8001
    network_mode: "host"
