version: "3"

services:
  app:
    build:
      dockerfile: server.dockerfile
      context: ./
    ports:
      - 8001:8001
    volumes:
      - ./configs:/src/configs
      - ./secrets:/src/secrets
      - ./:/src
